name: Node.js Snippets Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install snippets dependencies
        working-directory: ./snippets
        run: npm install

      - name: Run TypeScript compiler
        run: tsc

      - name: Lint and format check
        run: npm run lint
